/* Generated by make-abi-js.py from the LeaseVault and TestPositionFaucet artifacts.
   Do not edit: run `python make-abi-js.py` after changing the contract.
   check.sh fails if this file and the compiled contract disagree. */

window.TENURE_ABI = {
  /* signature -> selector and argument types */
  fn: {
    "MAX_BUILDER_FEE_DIVISOR()": { "sel": "0x945034d7", "inputs": [], "outputs": ["uint256"] },
    "MAX_FROZEN_BPS()": { "sel": "0x3f0f1372", "inputs": [], "outputs": ["uint16"] },
    "MAX_GRACE()": { "sel": "0xb0620f5b", "inputs": [], "outputs": ["uint32"] },
    "MAX_LISTING_DURATION()": { "sel": "0x9e02bd52", "inputs": [], "outputs": ["uint32"] },
    "MAX_TERM()": { "sel": "0x9886bf63", "inputs": [], "outputs": ["uint32"] },
    "MIN_GRACE()": { "sel": "0x5c9d9204", "inputs": [], "outputs": ["uint32"] },
    "MIN_TERM()": { "sel": "0xf0604829", "inputs": [], "outputs": ["uint32"] },
    "accruedRent(uint256)": { "sel": "0x08cf4870", "inputs": ["uint256"], "outputs": ["uint128"] },
    "balances(address)": { "sel": "0x27e235e3", "inputs": ["address"], "outputs": ["uint256"] },
    "buyBack(uint256)": { "sel": "0x053f9040", "inputs": ["uint256"], "outputs": [] },
    "cancel(uint256)": { "sel": "0x40e58ee5", "inputs": ["uint256"], "outputs": [] },
    "checkpointFreeze(uint256)": { "sel": "0x8976908e", "inputs": ["uint256"], "outputs": [] },
    "claimRent(uint256)": { "sel": "0x23c9b8c4", "inputs": ["uint256"], "outputs": [] },
    "collectFees(uint256)": { "sel": "0xb17acdcd", "inputs": ["uint256"], "outputs": [] },
    "deal(uint256)": { "sel": "0xc959c42b", "inputs": ["uint256"], "outputs": ["(address,address,uint256,bytes32,address,address,uint128,uint128,uint128,uint128,uint32,uint32,uint40,uint40,uint40,uint40,uint40,uint16,uint8,uint8,address,uint128)"] },
    "dealCount()": { "sel": "0xeadb3c9c", "inputs": [], "outputs": ["uint256"] },
    "fund(uint256)": { "sel": "0xca1d209d", "inputs": ["uint256"], "outputs": [] },
    "fund(uint256,address,uint128)": { "sel": "0x45bfe2ac", "inputs": ["uint256", "address", "uint128"], "outputs": [] },
    "graceEnd(uint256)": { "sel": "0xd24aafb6", "inputs": ["uint256"], "outputs": ["uint40"] },
    "leaseEnd(uint256)": { "sel": "0x2bd5467d", "inputs": ["uint256"], "outputs": ["uint40"] },
    "list(uint256,(uint128,uint128,uint128,uint32,uint32,uint32,uint16,uint8,address,uint128))": { "sel": "0x17763752", "inputs": ["uint256", "(uint128,uint128,uint128,uint32,uint32,uint32,uint16,uint8,address,uint128)"], "outputs": ["uint256"] },
    "positionOwed(uint256)": { "sel": "0xc7eca7d8", "inputs": ["uint256"], "outputs": ["address"] },
    "posm()": { "sel": "0x6f70a7fa", "inputs": [], "outputs": ["address"] },
    "release(uint256)": { "sel": "0x37bdc99b", "inputs": ["uint256"], "outputs": [] },
    "stateView()": { "sel": "0x4c4a3c25", "inputs": [], "outputs": ["address"] },
    "transferFinancierPosition(uint256,address)": { "sel": "0x6470b9b0", "inputs": ["uint256", "address"], "outputs": [] },
    "usdg()": { "sel": "0xf5b91b7b", "inputs": [], "outputs": ["address"] },
    "withdrawPosition(uint256)": { "sel": "0x525c12ea", "inputs": ["uint256"], "outputs": [] },
    "withdrawUSDG()": { "sel": "0x3e551d49", "inputs": [], "outputs": [] },
  },

  /* selector -> the name of the custom error the vault reverted with */
  err: {
    "0x6f73a538": "BadBuilderFee",
    "0x89f17dee": "BadEconomics",
    "0x20964459": "BadFrozenCap",
    "0x1c9e3a18": "BadGrace",
    "0xbf706cab": "BadListingDuration",
    "0x80869a7d": "BadProbe",
    "0xc8a081c6": "BadTerm",
    "0x8fc8ee31": "BuybackAboveSale",
    "0xebb8f04c": "GraceNotOver",
    "0x257874f9": "HasSubscriber",
    "0x534ec82d": "LeaseEnded",
    "0x398cfd02": "ListingExpired",
    "0xc301e07e": "NoLiquidity",
    "0x80cb55e2": "NotActive",
    "0xfa05b05d": "NotFinancier",
    "0x665c1c57": "NotListed",
    "0x5ec82351": "NotSeller",
    "0x797dba54": "NothingOwed",
    "0x7db3aba7": "OutOfRange",
    "0x6b49c94a": "PositionNotHeld",
    "0xab143c06": "Reentrancy",
    "0x702d6859": "SelfDeal",
    "0x39f1c8d9": "TransferFailed",
    "0xd92e233d": "ZeroAddress",
  },

  /* field order and width of the structs the page reads and writes, all static types */
  struct: {
    "Deal": [
      ["seller", "address"],
      ["financier", "address"],
      ["tokenId", "uint256"],
      ["poolId", "bytes32"],
      ["currency0", "address"],
      ["currency1", "address"],
      ["price", "uint128"],
      ["rent", "uint128"],
      ["buybackPrice", "uint128"],
      ["rentClaimed", "uint128"],
      ["term", "uint32"],
      ["grace", "uint32"],
      ["listingExpiry", "uint40"],
      ["fundedAt", "uint40"],
      ["pausedSince", "uint40"],
      ["pausedSeenAt", "uint40"],
      ["pausedTotal", "uint40"],
      ["maxFrozenBps", "uint16"],
      ["freezeProbe", "uint8"],
      ["state", "uint8"],
      ["builder", "address"],
      ["builderFee", "uint128"],
    ],
    "Terms": [
      ["price", "uint128"],
      ["rent", "uint128"],
      ["buybackPrice", "uint128"],
      ["term", "uint32"],
      ["grace", "uint32"],
      ["listingDuration", "uint32"],
      ["maxFrozenBps", "uint16"],
      ["freezeProbe", "uint8"],
      ["builder", "address"],
      ["builderFee", "uint128"],
    ],
  },

  /* Deal.state, in the order the enum declares it */
  state: ["None", "Listed", "Active", "BoughtBack", "Released", "Cancelled"],

  /* event name -> topic0, for the vault events the testnet quests are read from */
  ev: {
    "BoughtBack": "0xe33494317b40eab45e5c1f7e3ef5ffc941f366981339e1326ade11a75595b967",
    "Cancelled": "0xc41d93b8bfbf9fd7cf5bfe271fd649ab6a6fec0ea101c23b82a2a28eca2533a9",
    "FeesCollected": "0x0c2a2f565c7774c59e49ef6b3c255329f4d254147e06e724d3a8569bb7bd21ad",
    "FinancierTransferred": "0x5eaa966561b1bf1570c3b8a408451192296fb8a6e3d21918ac4ae1afa338d040",
    "Funded": "0x34d16fae85fa4050be2de8a6505ea86635dda307dc17afb27cad9d29f3b560dd",
    "Listed": "0x9ca24f02c8ad57d1453e3536fb4b166ffbcbb610eb778d3fcece887c54bea033",
    "Released": "0x97e5aed46bc81f03e962c6bef7511b2b3d12c57f9d3c8f4e63664ede4d404971",
    "RentClaimed": "0x396efe5aabae4c8c1ea28da525890643ad0f56c02003d1553064215b573e844d",
  },

  /* the test position faucet: its one call, and the event that names the position it gave */
  faucet: {
    "Given": "0xb6986524fdcf7d06d9c6f60ad9272cacf3a7e46aa4ec0bea8b6ee3d5873762dc",
    "give()": "0x9e96a23a",
  },

  /* Selectors of the token calls the page makes, which are not on the vault.
     Checked with `cast sig` rather than derived, because these contracts are not ours. */
  token: {
    "approve(address,uint256)": "0x095ea7b3",
    "allowance(address,address)": "0xdd62ed3e",
    "balanceOf(address)": "0x70a08231",
    "decimals()": "0x313ce567",
    "symbol()": "0x95d89b41",
    "getApproved(uint256)": "0x081812fc",
    "ownerOf(uint256)": "0x6352211e",
    "mint(address,uint256)": "0x40c10f19"
  }
};
